### ISSUE TITLE
Undefined property: WP_Error::$ID

### ISSUE THREAD

**Issue by Munnday** [NeosIT/active-directory-integration2#10]
After the last commit, I am unable to log in as a new user into the WordPress site.  Existing users are working without issues.

> Notice: Undefined property: WP_Error::$ID in C:\inetpub\wwwroot\Portal-Test\wp-content\plugins\active-directory-integration2-master\classes\Adi\Authentication\LoginService.php on line 446

The following appears in the debug log:

> [WARN ] Adi_User_Manager::findByActiveDirectoryUsername [line 122] WordPress user with wp_user_meta.samaccountname='wptest', user_login='wptest@domain.local' or user_login='wptest' could not be found  
[DEBUG] Adi_User_Manager::createAdiUser [line 176] Created new instance of User <no_wp_user_account>={id='', credentials='Credentials={login='wptest',sAMAccountName='wptest',userPrincipalName='wptest@domain.local'}'}  
[DEBUG] Adi_Authentication_LoginService::createUser [line 504] Checking preconditions for creating new user User <no_wp_user_account>={id='', credentials='Credentials={login='wptest',sAMAccountName='wptest',userPrincipalName='wptest@domain.local'}'}  
[DEBUG] Adi_User_Helper::getRandomPassword [line 162] Setting local password to the used for this login. 
[ERROR] Core_Util_LoggerUtil::error [line 36]  
[ERROR] Adi_Authentication_LoginService::createOrUpdateUser [line 482] Unable to update or create 'User wptest={id='', credentials='Credentials={login='wptest',sAMAccountName='wptest',userPrincipalName='wptest@domain.local'}'}':

**Comment by Munnday** [comment]
The issue was cause by a local WordPress user having the same email address as the AD user trying to sync.

**Comment by schakko** [comment]
It does not seem that you have the latest commit in your local repository. The log error

    [ERROR] Adi_Authentication_LoginService::createOrUpdateUser [line 482] Unable to update or create

does not exist in line 482 but in 484. Would you please check that your local branch is at 90caee4?

**Comment by Munnday** [comment]
Just double checked, the line count is different as I was messing around with the postAuthentication function and moved the opening { when setting it back to the original (see screenshot )
![error](https://cloud.githubusercontent.com/assets/1051709/16294307/3e8e6e5e-3963-11e6-8432-d2cfdf2ed65a.PNG)

**Comment by schakko** [comment]
Okay, thank you!
We have identified at least the notification issue. @MeissnerDa will keep you updated.

**Comment by MeissnerDa** [comment]
I fixed the duplicate email prevention notification bug. You will now see a log error message if the creation of an user failed because of an existing user with the same email address. ADI prevents the creation of users using the same email address by default. You can allow the creation by setting the "Configuration > User > Email address conflict handling" option to "Allow". I hope I could help you with your problem.

**Comment by Munnday** [comment]
Pretty sure this one has been taken care off?

**Comment by MeissnerDa** [comment]
We implemented a fix and tested everything successfully on our system. You should now receive log messages informing you about the fact that an user could not be created, because there is already an user with the same email address in your WordPress database. You have the possibility to turn this off by switching "Configuration > User > Email address conflict handling" from "Prevent" to "Allow". Can you confirm that everything works for you ?

**Comment by FatSquirrel93** [comment]
Closed due to inactivity
