### ISSUE TITLE
Sync AD forest

### ISSUE THREAD

**Issue by RustyRivet** [NeosIT/active-directory-integration2#126]
Hi there,

We authenticate using our GC on our root domain (company.xyz) and have a couple of domains under the root (e.g. domain1.company.xyz and domain2.xyz). We permit users if they're in various universal groups across the domains, authentication using NADI works great.

We're looking at using the Sync to WP feature, but it seems to only add new users who are in groups on the same domain which NADI is verified against. If the user is part of a subdomain, they are not added.

Looking at your support material I saw the following:

> Does Next ADI support domain forests?
> No, not fully. You can configure Next ADI to use one of your Global Catalogs for authentication. Users can login but Sync to WordPress/Active Directory will not work. If you need really need this feature please contact us.

I suspect this is confirming that the behaviour we are seeing is expected... as we really need this feature, I'm making contact so hopefully you can advise a process or solution which may work?

Thanks for your time,
Rusty.

**Comment by schakko** [comment]
Hi Rusty,
there is not really a process or solution I can present you right now. Over the years we have received some requests about this, but too irregularily to fundraise the feature. Due to the complexity (NADI compatibility with WordPress multisite, multiple AD Domains per site) the effort is too high as we can implement it without a larger external amount of money.

**Comment by schakko** [comment]
Fetching users from a Global Catalog and getting Kerberos SSO working in AD forest environments is part of the upcoming NADI 2.2.0 version with the [Active Directory Forest premium extension ](https://active-directory-wp.com/premium-extension/active-directory-forest/).
