### ISSUE TITLE
twig_cycle colliding with another plugin (all-in-one-event-calendar)

### ISSUE THREAD

**Issue by fredand** [NeosIT/active-directory-integration2#165]
Error in latest version of WP, All in one event calendar, NAD, php version 8.1

**Fatal error:** 
Cannot redeclare twig_cycle() (previously declared 
in /data/[redacted]/wp-content/plugins/all-in-one-event-calendar/vendor/twig/Extension/Core.php:360) 
in /data/[redacted]/wp-content/plugins/next-active-directory-integration/vendor/twig/twig/src/Extension/CoreExtension.php on line 324

**Comment by schakko** [comment]
This  is not an easy-to-fix issue.
1. Either we replace the current Twig templates with pure-HTML/PHP ones
2. or we use something like [php-scoper](https://github.com/humbug/php-scoper), [strauss](https://github.com/BrianHenryIE/strauss) or [mozart](https://github.com/coenjacobs/mozart) to prefix vendor packages so that they don't pollute the global namespace.

**Comment by schakko** [comment]
@fredand I've just created a pre-release for 3.0.0. The pre-release has *a lot* of changes, you should backup your current NADI installation.

**Comment by fredand** [comment]
I'm far from fluent navigating GitHub... i tried (to download the correct release) and had to disable row 29 in index.php... after that when i tried "activate for network" (using multi-site) i got a "critical error" displayed in the browser but nothing in "debug.log" or in Apache error logs.

**Comment by schakko** [comment]
@fredand I've created a new pre-relase which should fix the issues.

**Comment by schakko** [comment]
Should be fixed by now
