### ISSUE TITLE
Apache warning with PHP8.1

### ISSUE THREAD

**Issue by ghillebrand** [NeosIT/active-directory-integration2#167]
Hi,
Migrating a site to WP 6.1.1 on PHP 8.1, Apache (On Turnkey 17.1 (Debian 11?) ) gives the following warning only when your run a test account from the configuration page. It does not occur on each authentication call from the user login page.
It is most probably minor, but I am reporting it in the interests of stability and not breaking as things go forward.

`[Thu Dec 01 06:39:41.525740 2022] [php:warn] [pid 7880] [client 172.16.6.5:50906] PHP Warning:  ldap_search(): Search: No such object in /var/www/wordpress/wp-content/plugins/next-active-directory-integration/vendor/adLDAP/adLDAP.php on line 1490, referer: http://172.16.0.164/wp-admin/admin.php?page=next_ad_int_blog_options`

Thanks for a great tool.
Grant

**Comment by schakko** [comment]
Hi @ghillebrand,
thank you for your kind words!

This might already have been fixed with #166. Can you make a backup of your `vendor/adLDAP/adLDAP.php`, replace it with the `adLDAP.php` from https://github.com/NeosIT/active-directory-integration2/commit/b6e4fa2716a5abeaa9846683fe483f1938017274 and see if it works?

**Comment by schakko** [comment]
Should be fixed with today's 2.3.6.

**Comment by ghillebrand** [comment]
Thank you - I have been a bit snowed under, and unable to test on my side - apologies!
