### ISSUE TITLE
users are invisible

### ISSUE THREAD

**Issue by ithowest** [NeosIT/active-directory-integration2#26]
Our setup at our school:
It's multisite wordpress. We've imported all the users (+/- 10 000) through the sync button. Via curl or wget it fails (that's issue 1). The sync works via the sync button so all my users are imported in the root site. 
Next I create a new site and add one our students as an admin. When I look at that site I still can see the ADI user so no problems yet. But when the users logs in for the first time. He loses his permissions and becomes unvisible in the userlist of that site. In my permission tab I've added a wordpress mapping for the staff of the school but no group mapping at all for our students. 
I cannot add a mapping for our students because they may not read the blog of their fellow students. So if there's no mapping, I presume the ADI2 plugin stays off the existing permissions of a ADI user? But that's not the case...

Only the owner (student) and the staff may read their blog. Other plugins I use to accomplish this is "private by default". It basically makes every page and post you create private. You need editor or admin rights to see the posts...

**Comment by MeissnerDa** [comment]
Hello ithowest,
Thank you for reporting those bugs. I already added the curl/wget bug to our internal issue tracker. Furthermore our developer team is currently discussing the second problem. Could you tell me, if you have the option "User > Automatic user synchronization" enabled ? This could explain why your students lose their "Administrator" role. When your student tries to login for the first time he/she gets synchronized with the Active Directory. Since there is no "role equivalent mapping" between the Active Directory "Student" group and a WordPress role, Next ADI removes the "Administrator" role from your students WordPress account. We will think about a solution for this problem as soon as possible. 

Have a nice day
MeissnerDa

**Comment by FatSquirrel93** [comment]
Hey @ithowest 

I am trying to resolve your wget/curl problem. I am unable to replicate your problem on my machine/system.
Can you provide any kind of output when using wget/curl to trigger a sync?

**Comment by ithowest** [comment]
curl output: 
[INFO ] Start of Sync to WordPress <br />[INFO ] LDAP connection is *not* encrypted <br />[INFO ] In group 'sg_personeel' are 904 members. <br />[INFO ] In group 'sg_studenten' are 8038 members. <br />

in debug log:
2016-10-07 14:18:57 [INFO ] NextADInt_Adi_Synchronization_WordPress::prepareForSync [line 159] Start of Sync to WordPress ^M
2016-10-07 14:18:57 [INFO ] NextADInt_Ldap_Connection::createConfiguration [line 101] LDAP connection is *not* encrypted ^M
2016-10-07 14:18:57 [INFO ] NextADInt_Ldap_Connection::findAllMembersOfGroups [line 529] In group 'sg_personeel' are 904 members. ^M
2016-10-07 14:19:03 [INFO ] NextADInt_Ldap_Connection::findAllMembersOfGroups [line 529] In group 'sg_studenten' are 8038 members. ^M

And then it stops....

**Comment by ithowest** [comment]
@MeissnerDa 
If I disable the automatic user sync, tt seems to be fixed when there's no mapping of AD group to WP roles. But when there is at least one entry in the mapping it still syncs to active directory and the users loose their permissions. Hope this helps you out.

**Comment by MeissnerDa** [comment]
@ithowest Thank you for the information. I found a bug which seems to be the reason for the roles to be removed. We will take a look at it and try to fix this problem as soon as possible. 

Have a nice day
MeissnerDa

**Comment by schakko** [comment]
No response since 4 weeks. I'll close this issue.
