### ISSUE TITLE
Multiple Base-DNs

### ISSUE THREAD

**Issue by ReneLuecking** [NeosIT/active-directory-integration2#32]
Ist it possible to use more than kne Base-DN?

**Comment by ReneLuecking** [comment]
*one

**Comment by schakko** [comment]
This is not implemented because it can lead to a lot of LDAP calls during the authentication. If you use multiple UPN suffixes each of the UPN suffix has to be tested against all defined base DNs.
Can you explain the requirement for multiple base DNs instead of using an OU based more upper in the hierarchy?

**Comment by ReneLuecking** [comment]
The company I work for has (for historical reason) 4 different base DNs and every base DN has its own UPN. I have to find out, if i can find all base DNs under the same OU, but i don't think so

**Comment by schakko** [comment]
You could try to use the Global Catalog as DC. This *could* work.

**Comment by ReneLuecking** [comment]
I just want to add, that it works using the Global Catalog.

**Comment by schakko** [comment]
Thank you for the response, I have just added the information to our documentation!
