### ISSUE TITLE
User Roles are lost upon login

### ISSUE THREAD

**Issue by requincreative** [NeosIT/active-directory-integration2#33]
I was finally able to get Next AD Integration installed and migrated settings from AD Integration v1 however when users login their WordPress User Roles are lost?  

I have some defined ad -> wp user roles defined but not all users have an ad equivalent in wordpress

Any thoughts?

**Comment by FatSquirrel93** [comment]
Hey @requincreative 
We are glad to hear you have almost everything set up.
First of, you said 
> not all users have an ad equivalent in wordpress
Does that mean, that some of your users do have the correct role?

You can always check the log (if you have logging enabled) and check the detailed output.
Also make sure the role equivalent groups are correctly entered. They are case sensitive.

**Comment by requincreative** [comment]
Thank you.

The issue I have is because not all of my users have role equivalent groups in AD.  For instance my AD users that are designated Administrators in WP are kicked out of the Administrators group in WP when they log in.  The only user that maintains the proper WP role is not an AD synced user.

Is it not possible to skip over users who do not have an explicit equivalent role defined in the plugin setting?

**Comment by schakko** [comment]
@requincreative We had this discussion internally and decided to go for explicit definition of role assignments. The reason was (still is) that the security has priority: What happens if you move a user in one of your security groups into a new, lower-permissioned security group. The new security group would not have been mapped in NADI but the user would still have the permissions.
Because of this we decided to go for explicit definitions.

A (pragmatical) solution for your problem would be to create a security group for your WP administrators and assign the WordPress administrators to this security group.

If you need a solution to exclude special users from security group mapping, please get in touch with us on http://active-directory-wp.com/ to receive a written offer.
