### ISSUE TITLE
Plugin deactivating Itself if site is accessible from more than one domain

### ISSUE THREAD

**Issue by chadhayton** [NeosIT/active-directory-integration2#61]
We have a Wordpress setup that uses a different URL for access to the admin screens than we use for the publicly accessible site.  This setup appears to trigger the plugin's auto-deactivation routine.  It looks like a similar problem was reported in Issue #42, but no solution was posted there.

Below is the code I think it getting fired.  Is my diagnosis correct that accessing the site from more than one domain will deactivate the plugin? Is there a work-around for this?  Why does it matter if we use more than one domain to access the site?

Function found in next-active-directory-integration/classes/Adi/Requirements.php:
```
public function check($showErrors = true, $includeActivationCheck = false)
	{
		try {
			$this->requireWordPressVersion($showErrors);
			$this->requireLdap($showErrors);
			$this->requireMbstring($showErrors);
                        $this->requireOpenSSL($showErrors);

			// check if this WordPress instance has more than 10,000 blogs/sites
			if (is_multisite()) {
				$this->preventTooManySites();

				// must be only executed during activation and *not* during execution
				if ($includeActivationCheck) {
					$this->preventSiteActivation();
				}
			}

			// deactivate deprecated ADI version if requirements are met
			$this->deactivateDeprecatedVersion();
		} catch (Exception $e) {
			// at this moment the plugin.php is not loaded
			NextADInt_Core_Util::native()->includeOnce(ABSPATH . 'wp-admin/includes/plugin.php');

			// ensure that the plug-in has not been enabled
			deactivate_plugins(NEXT_AD_INT_PLUGIN_FILE);

			return false;
		}

		return true;
	}
```

**Comment by MeissnerDa** [comment]
Hello @chadhayton,

could you please give me more information about what the actual problem is ? Did I understand you correct that you have 2 domains (e.g. www.testdomainA.com and www.testdomainB.com) pointing at the same WordPress instance and that if you access one of them NADI gets deactivated ? 

The snipped you posted is not related to anything domain specific. The code checks if you are running a multisite environment and if it has less than 1000 sites. 

"deactivateDeprecatedVersion();" disables the old version of the plugin called "Active Directory Integration".

Are you trying to run NADI in a WordPress multi site environment ? 

Best regards,
meissnerDa
