### ISSUE TITLE
Sync to Wordpress

### ISSUE THREAD

**Issue by Delticgrp** [NeosIT/active-directory-integration2#65]
Hi, 
I have installed the NADI plugin fine and I have authenticated to LDAP on my domain.  However, when I try and sync with WordPress using a service account I get the error message;

SID of user '***.***.local' could not be retrieved. Is the base DN correct? Does the userPrincipalName '***.***.local' exist and not only its sAMAccountName?'

I know that the credentials are correct as I have used this account to authenticate the plugin and I have also run the test authentication which runs fine.  I have also checked to see if the service account has read permissions to the base DN which it does.  Can you suggest anything that might be causing this issue??

**Comment by MeissnerDa** [comment]
Hello @Delticgrp ,
in order to configure NADI correctly please take a look at our documentation at https://active-directory-wp.com/docs/Getting_Started.html.

If you would like us to take a deeper look at your problem please consider to buy a support license at https://active-directory-wp.com/shop-overview/. 

Best regards,
meissnerDa
