### ISSUE TITLE
AD Password is not set correctly on Import

### ISSUE THREAD

**Issue by kellerisddev** [NeosIT/active-directory-integration2#71]
When the user profiles are created in WordPress the initial password is not set correctly.

Set local password on first successful login	True
Allow local password changes	False
Fallback to local password	 False
Automatic password update	 True
Enable lost password recovery	 True

I have debugging turned on but it does not capture any information on failed logins.  What is the best method to figure this out.

**Comment by MeissnerDa** [comment]
Hello @kellerisddev ,

at the moment all our developers are busy with other projects so I can not give you any ETA when we will be able to take a look at this and can try to reproduce the problem. I will add this to our issue tracker and inform you once we took a look at it.

Best regards,
meissnerDa

**Comment by MeissnerDa** [comment]
Hello @kellerisddev,

with NADI 2.1.3 we fixed a bug where the local password was not set properly when "Automatic user update" was enabled aswell. 

However, "Set local password on first successful login" enabled only makes sense if you enable "Fallback to local password" aswell. Otherwise your users wont be able to authenticate against the local WordPress password authentication if the Active Directory Server is unreachable.

If you own a valid support license you can contact us via the support ticket system at https://active-directory-wp.com/ so that we can take a look at your logfiles and NADI configurations.

You can also take a look at our documentation to setup NADI correctly. https://active-directory-wp.com/docs/Getting_Started.html

Best regards,
meissnerDa
